branch-defaults:
  master:
    environment: Omoads-env
  test_branch:
    environment: omoads-deploy
environment-defaults:
  omoads-deploy:
    branch: null
    repository: null
global:
  application_name: omoads
  branch: null
  default_ec2_keyname: tegkhanna
  default_platform: Python 3.4
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
