branch-defaults:
  master:
    environment: Omoads-env-py3
environment-defaults:
  Omoads-env-py3:
    branch: null
    repository: null
global:
  application_name: omoads
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.1
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
