# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('type_media', models.CharField(max_length=200)),
                ('lighted', models.BooleanField()),
                ('dimensions', models.BigIntegerField()),
                ('cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('lattitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
    ]
