# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='cost',
            new_name='banner_cost',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='lattitude',
            new_name='banner_lattitude',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='lighted',
            new_name='banner_lighted',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='longitude',
            new_name='banner_longitude',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='region',
            new_name='banner_region',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='type_media',
            new_name='owner_id',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_dimensions',
            field=models.CharField(choices=[('0', '50x10'), ('1', '40x10'), ('2', '30x10'), ('3', '20x10')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_id',
            field=models.CharField(default=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('gantry', 'Gantry'), ('unipole', 'Unipole')], default='gantry', max_length=100),
        ),
    ]
