# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170711_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
