# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170712_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_lighted',
            field=models.CharField(choices=[('f', 'Front Lit'), ('b', 'Back Lit'), ('n', 'Not Lighted')], default='n', max_length=100),
        ),
    ]
