# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20170719_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=30)),
                ('agency_state', models.CharField(max_length=50)),
                ('agency_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=50)),
                ('customer_password', models.CharField(max_length=50)),
                ('customer_contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_amt', models.IntegerField()),
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('hoarding_no', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Info',
            fields=[
                ('pole_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Order')),
            ],
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner_region',
            new_name='banner_landmark',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_facing',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(default='omoads/Image/banner1.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Agency'),
        ),
    ]
