# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-23 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20170723_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='owner_id',
            new_name='agency_id',
        ),
    ]
